name: Release to npm

on:
  push:
    paths:
      - 'package.json'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Deps
        run: npm i
      - name: Login to NPM
        run: npm login xstars_dev ${{ secrets.NODE_AUTH_TOKEN }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release to npm
        run: npm run release
