name: Release to npm

on:
  push:
    paths:
      - 'package.json'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to npm
        run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release to npm
        if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'package.json')
        run: npm run release
